### ISSUE TITLE
Disable Thermals

### ISSUE THREAD

**Issue by ShineDwarf** [A3Wasteland/ArmA3_Wasteland.Stratis#102]
Since Tanks DLC update, Thermals no longer appear to be disabled even with The config on. Noticing this on all vehicle weapons which would normally have it as well as commander slots.

**Comment by AgentRev** [comment]
I did not experience this bug during testing...

**Comment by ShineDwarf** [comment]
Hmm we'll take another look to see if anything been messed up along the way. I don't remember us altering any files pertaining to it, but anythings possible.
