### ISSUE TITLE
unlimited ammunition able to be stored in to uniform

### ISSUE THREAD

**Issue by soulkobk** [A3Wasteland/ArmA3_Wasteland.Stratis#105]
with the current v1.4c dev build (https://github.com/A3Wasteland/ArmA3_Wasteland.Stratis) there seems to be an issue with gun store ammunition purchases to where it allows an unlimited amount of ammunition in to a players uniform.

scenario... 
- equip player with a full ghille uniform, carrier lite vest, bergen backpack.
- at gun store, purchase mk200 LMG and proceed to purchase ammo until the uniform/vest/backpack become full and won't allow any more purchases.
- close store gui.
- open inventory and remove magazines from vest on to the ground.
- re-open store, go to mk200 LMG, proceed to purchase unlimited rounds of ammunition that is 'forced?' in to the uniform.

testing environment...
- windows ultimate x64
- arma 3 1.82.144647 (eden)
- saving profilenamespace

-soul.

**Comment by AgentRev** [comment]
fixed - I stumbled upon [this](https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues/425) yesterday but there were actually 4 lines to fix and I had only done 2

**Comment by soulkobk** [comment]
ok, great.
