### ISSUE TITLE
setupMissionArrays sqf, what is  weight?

### ISSUE THREAD

**Issue by rhmkds** [A3Wasteland/ArmA3_Wasteland.Stratis#109]
on \server\missions\setupMissionArrays.sqf, what is  weight value?
is mean more higher more enemy units?
// Mission filename, weight
 ["mission_ArmedDiversquad", 1],
["mission_Coastal_Convoy", 1],

**Comment by AgentRev** [comment]
It's the chances of that mission being selected relative to the sum of all weights.
