### ISSUE TITLE
Error on Linux Arma 3 server

### ISSUE THREAD

**Issue by jondavis0787** [A3Wasteland/ArmA3_Wasteland.Stratis#14]
File mpmissions\__cur_mp.stratis\client\systems\adminPanel\dialog\objectSearch.hpp, line 947: Config: ';' used as a separator in the array

https://github.com/A3Wasteland/ArmA3_Wasteland.Stratis/blob/Development_Main/client/systems/adminPanel/dialog/objectSearch.hpp#L1061 

remove the ; please I fixed it already on my mission along with other stuff and the other issue is that the vehicle store won't work

**Comment by newtondev** [comment]
Hi JoSchaap,

I can definitely say that the ArmA 3 Linux server outperforms windows any day. We are running an 8 core 3.2Ghz server with 16GB of RAM with 3x ArmA 3 servers running on it using my port of iniDB for linux and the performance is amazing. 

Thanks for all the hard work you guys put into this mission file, it is much appreciated.

**Comment by JoSchaap** [comment]
thanks for the info and complement. 
Since this is an old (and resolved) issue i will close this again though.
we also have forums at: http://forums.a3wasteland.com
