### ISSUE TITLE
ArmA3_Wasteland.Stratis v1.1 Not work on my game

### ISSUE THREAD

**Issue by zhaoxg686** [A3Wasteland/ArmA3_Wasteland.Stratis#58]
Can only display in the middle "Welcome to A3Wasteland, please wait for your client to initialize",And then nothing happens.

**Comment by AgentRev** [comment]
Please learn how to use the -showScriptErrors param and provide RPT logs before you ask for help here

**Comment by zhaoxg686** [comment]
=====================================================================
== J:\GAME\Arma 3\arma3.exe
== "J:\GAME\Arma 3\arma3.exe" -showScriptErrors

Exe timestamp: 2013/09/12 14:55:24
Current time:  2015/01/18 09:10:20

Type: Public Beta
Branch: Stable
Version: 1.00.109911

Allocator: J:\GAME\Arma 3\dll\tbb4malloc_bi.dll
=====================================================================

Updating base class ->Base, by a3\dubbing_radio_f\config.bin/CfgHQIdentities/PAPA_BEAR/
Updating base class ->Base, by a3\dubbing_radio_f\config.bin/CfgHQIdentities/AirBase/
Updating base class ->RscText, by a3\ui_f\config.bin/RscDisplayCapture/controls/TimeLines/
Updating base class RscControlsGroup->RscControlsGroupNoScrollbars, by a3\ui_f\config.bin/RscDisplayMain/controls/ModIcons/
Updating base class RscPicture->RscPictureKeepAspect, by a3\ui_f\config.bin/RscDisplayMain/IconPicture/
Updating base class RscListBox->RscCombo, by a3\ui_f\config.bin/RscDisplayCustomizeController/Steepness/
Updating base class ->RscStandardDisplay, by a3\ui_f\config.bin/RscDisplayControlSchemes/
Updating base class ButtonOK->RscButtonMenuCancel, by a3\ui_f\config.bin/RscDisplayControlSchemes/controls/ButtonCancel/
Updating base class RscButton->RscButtonMenuOK, by a3\ui_f\config.bin/RscDisplayControlSchemes/controls/ButtonOK/
Updating base class RscPicture->RscPictureKeepAspect, by a3\ui_f\config.bin/RscDisplayFileSelectImage/controls/OverviewPicture/
Updating base class RscShortcutButton->RscButtonMenuCancel, by a3\ui_f\config.bin/RscDisplayFieldManual/controls/ButtonCancel/
Updating base class RscButton->RscButtonMenuCancel, by a3\ui_f\config.bin/RscDisplayPublishMission/controls/ButtonCancel/
Updating base class RscShortcutButton->RscButtonMenuOK, by a3\ui_f\config.bin/RscDisplayPublishMissionSelectTags/controls/ButtonOK/
Updating base class ButtonOK->RscButtonMenuCancel, by a3\ui_f\config.bin/RscDisplayPublishMissionSelectTags/controls/ButtonCancel/
Updating base class ->RscSubmenu, by a3\ui_f\config.bin/RscMainMenu/
Cannot update non class from class a3\ui_f\config.bin/RscCallSupport/Items/
Cannot update non class from class a3\ui_f\config.bin/RscRadio/Items/

==== Loaded addons ====

dta\bin.pbo - unknown
dta\core.pbo - 0
dta\languagecore_f.pbo - 55986
addons\a3.pbo - unknown
addons\air_f.pbo - 55395
addons\air_f_beta.pbo - 55469
addons\air_f_gamma.pbo - 55296
addons\animals_f.pbo - 53513
addons\animals_f_beta.pbo - 54975
addons\anims_f.pbo - 55479
addons\anims_f_data.pbo - 55460
addons\armor_f.pbo - 53513
addons\armor_f_beta.pbo - 55401
addons\armor_f_gamma.pbo - 55401
addons\baseconfig_f.pbo - 43414
addons\boat_f.pbo - 54949
addons\boat_f_beta.pbo - 54453
addons\boat_f_gamma.pbo - 55779
addons\cargoposes_f.pbo - 55395
addons\characters_f.pbo - 55794
addons\characters_f_beta.pbo - 55401
addons\characters_f_gamma.pbo - 55779
addons\data_f.pbo - 55794
addons\drones_f.pbo - 55328
addons\dubbing_f.pbo - 55351
addons\dubbing_f_beta.pbo - 55170
addons\dubbing_f_gamma.pbo - 55217
addons\dubbing_radio_f.pbo - 55654
addons\dubbing_radio_f_data.pbo - 55654
addons\editor_f.pbo - 53723
addons\functions_f.pbo - 55873
addons\languagemissions_f.pbo - 55986
addons\languagemissions_f_beta.pbo - 55986
addons\languagemissions_f_gamma.pbo - 55986
addons\language_f.pbo - 55986
addons\language_f_beta.pbo - 55986
addons\language_f_gamma.pbo - 55986
addons\map_altis.pbo - 55473
addons\map_altis_data.pbo - 55473
addons\map_altis_data_layers.pbo - 54531
addons\map_altis_data_layers_00_00.pbo - 54531
addons\map_altis_data_layers_00_01.pbo - 54531
addons\map_altis_data_layers_01_00.pbo - 54531
addons\map_altis_data_layers_01_01.pbo - 54531
addons\map_altis_scenes_f.pbo - 55073
addons\map_data.pbo - 54886
addons\map_stratis.pbo - 55395
addons\map_stratis_data.pbo - 52631
addons\map_stratis_data_layers.pbo - 49811
addons\map_stratis_scenes_f.pbo - 55073
addons\misc_f.pbo - 54927
addons\missions_f.pbo - 55460
addons\missions_f_beta.pbo - 55527
addons\missions_f_beta_data.pbo - 55296
addons\missions_f_beta_video.pbo - 49010
addons\missions_f_data.pbo - 53723
addons\missions_f_gamma.pbo - 55794
addons\missions_f_gamma_data.pbo - 55501
addons\missions_f_gamma_video.pbo - 52884
addons\missions_f_video.pbo - 52434
addons\modules_f.pbo - 55500
addons\modules_f_beta.pbo - 55460
addons\modules_f_beta_data.pbo - 52079
addons\modules_f_data.pbo - 51786
addons\music_f.pbo - 55469
addons\music_f_music.pbo - 55431
addons\plants_f.pbo - 54531
addons\roads_f.pbo - 53255
addons\rocks_f.pbo - 54961
addons\signs_f.pbo - 54477
addons\soft_f.pbo - 55401
addons\soft_f_beta.pbo - 55401
addons\soft_f_gamma.pbo - 55779
addons\sounds_f.pbo - 55395
addons\sounds_f_vehicles.pbo - 55296
addons\sounds_f_weapons.pbo - 55296
addons\static_f.pbo - 55176
addons\static_f_beta.pbo - 53790
addons\static_f_gamma.pbo - 55779
addons\structures_f.pbo - 55458
addons\structures_f_data.pbo - 55395
addons\structures_f_households.pbo - 55395
addons\structures_f_ind.pbo - 55395
addons\structures_f_mil.pbo - 55395
addons\structures_f_wrecks.pbo - 55395
addons\uifonts_f.pbo - 55794
addons\uifonts_f_data.pbo - 55794
addons\ui_f.pbo - 55779
addons\ui_f_data.pbo - 55779
addons\weapons_f.pbo - 55351
addons\weapons_f_beta.pbo - 55779
addons\weapons_f_gamma.pbo - 55351

=======================

DX11 - Initializing DX11 engine.
DX11 - Using DXGI adapter 0 (detected in config).
DX11 - Using DXGI adapter 0.
    - adapter description : NVIDIA GeForce GTX 560 Ti  
    - adapter vendor ID : 4318
    - adapter device ID : 4608
    - adapter subsys ID : 0
    - adapter revision  : 161
    - dedicated video memory : 1024917504
    - dedicated system memory : 0
    - shared system memory : 3221106688
Error: JoystickDevices - CoInitilizeEx return 80010106
Error: CoInitilizeEx (XAudio2-1st trial) return 80010106
PhysX3 SDK Init started ...
PhysX3 SDK Init ended.
No more slot to add connection at 033057 (3386.8,5735.4)
Attempt to override final function - bis_functions_list
Attempt to override final function - bis_functions_listpreinit
Attempt to override final function - bis_functions_listpostinit
Attempt to override final function - bis_functions_listrecompile
Attempt to override final function - bis_fnc_missiontaskslocal
Attempt to override final function - bis_fnc_missionconversationslocal
Attempt to override final function - bis_fnc_missionflow
  bin\config.bin/CfgMovesMaleSdr/States/AmovPknlMevaSrasWpstDr.InterpolateTo: Bad move AmovPknlMsprSlowWpstDf_AmovPpneMstpSrasWpstDnon
  bin\config.bin/CfgMovesMaleSdr/States/AmovPknlMevaSrasWpstDl.InterpolateTo: Bad move AmovPknlMsprSlowWpstDf_AmovPpneMstpSrasWpstDnon
Animation a3\anims_f_epa\data\anim\sdr\cts\custom\a_in\acts_percmstpslowwrfldnon_handup2b.rtm not found or empty
Animation a3\anims_f_epa\data\anim\sdr\cts\custom\a_in\acts_percmstpslowwrfldnon_handup2c.rtm not found or empty
Animation a3\anims_f_epa\data\anim\sdr\cts\custom\a_in\acts_percmstpslowwrfldnon_handup1b.rtm not found or empty
Animation a3\anims_f_epa\data\anim\sdr\cts\custom\a_in\acts_percmstpslowwrfldnon_handup1c.rtm not found or empty
Animation a3\anims_f_epa\data\anim\sdr\cts\custom\a_in\acts_walkingchecking.rtm not found or empty
Animation a3\anims_f_epa\data\anim\sdr\cts\custom\b_in\acts_unconsciousstandup.rtm not found or empty
Animation a3\air_f_delta\plane_fighter_01\data\anim\kia_plane_fighter_01_pilot.rtm not found or empty
Animation a3\air_f_delta\plane_fighter_01\data\anim\plane_fighter_01_pilot.rtm not found or empty
Animation a3\air_f_beta\heli_attack_01\data\anim\heli_attack_01_pilot_kia.rtm not found or empty
Animation a3\air_f_beta\heli_attack_01\data\anim\pilot_heli_light_02_kia.rtm not found or empty
Animation a3\air_f_beta\heli_attack_01\data\anim\copilot_heli_light_02_kia.rtm not found or empty
Animation a3\air_f_delta\plane_transport_01\data\anim\kia_plane_transport_01_pilot.rtm not found or empty
Animation a3\air_f_delta\plane_transport_01\data\anim\plane_transport_01_pilot.rtm not found or empty
soldier[O_Soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
soldier[O_Soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
soldier[O_Soldier_LAT_F]:Some of magazines weren't stored in soldier Vest or Uniform?
soldier[O_Soldier_LAT_F]:Some of magazines weren't stored in soldier Vest or Uniform?
soldier[O_Soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
soldier[O_Soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
soldier[O_Soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
soldier[O_Soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
soldier[B_soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
soldier[B_soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
soldier[B_soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
soldier[B_soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
soldier[B_soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
soldier[B_soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
control[CA_ValuePrivate]: Unexpected control type [42]
control[CA_ValuePrivate]: Unexpected control type [42]
Unable to get my public IP address
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\empty.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\empty.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\empty.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\empty.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\acc\reticle_hamr.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\empty.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\empty.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\acc\reticle_arco_f.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\acc\reticle_arco_f.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\empty.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\empty.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\acc\reticle_arco_f.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\empty.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\empty.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\acc\reticle_hamr.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\empty.p3d]
LODShape::AddLoadHandler: Handler not present in shape [a3\weapons_f\empty.p3d]
Warning Message: mpmissions\A3Wasteland_v1.1.Stratis\mission.sqm/Mission/Groups/Item36/Vehicles/Item0.vehicle: Vehicle class HeadlessClient_F no longer exists
Warning Message: mpmissions\A3Wasteland_v1.1.Stratis\mission.sqm/Mission/Vehicles/Item245.vehicle: Vehicle class Land_Atm_01_F no longer exists
Warning Message: mpmissions\A3Wasteland_v1.1.Stratis\mission.sqm/Mission/Vehicles/Item246.vehicle: Vehicle class Land_Atm_02_F no longer exists
Warning Message: mpmissions\A3Wasteland_v1.1.Stratis\mission.sqm/Mission/Vehicles/Item247.vehicle: Vehicle class Land_Atm_01_F no longer exists
Warning Message: mpmissions\A3Wasteland_v1.1.Stratis\mission.sqm/Mission/Vehicles/Item248.vehicle: Vehicle class Land_Atm_02_F no longer exists
Warning Message: mpmissions\A3Wasteland_v1.1.Stratis\mission.sqm/Mission/Vehicles/Item249.vehicle: Vehicle class Land_Atm_01_F no longer exists
Warning Message: mpmissions\A3Wasteland_v1.1.Stratis\mission.sqm/Mission/Vehicles/Item250.vehicle: Vehicle class Land_Atm_01_F no longer exists
Warning Message: No entry 'bin\config.bin/CfgMarkerColors.ColorWEST'.
Warning Message: No entry '.color'.
Warning Message: Size: '/' not an array
Warning Message: Size: '/' not an array
Warning Message: No entry 'bin\config.bin/CfgMarkerColors.ColorEAST'.
Warning Message: No entry '.color'.
Warning Message: Size: '/' not an array
Warning Message: Size: '/' not an array
Warning Message: No entry 'bin\config.bin/CfgMarkerColors.ColorGUER'.
Warning Message: No entry '.color'.
Warning Message: Size: '/' not an array
Warning Message: Size: '/' not an array
Warning Message: No entry 'bin\config.bin/CfgMarkerColors.ColorCIV'.
Warning Message: No entry '.color'.
Warning Message: Size: '/' not an array
Warning Message: Size: '/' not an array
Type HeadlessClient_F is not VehicleType
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <n
{
A3W_atmArray = [];
};

A3W_atmArray pushBack _atm;
>
  Error position: <pushBack _atm;
>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupMissionATM.sqf, line 26
Error in expression <n
{
A3W_atmArray = [];
};

A3W_atmArray pushBack _atm;
>
  Error position: <pushBack _atm;
>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupMissionATM.sqf, line 26
Attempt to override final function - bis_functions_list
Attempt to override final function - bis_functions_listpreinit
Attempt to override final function - bis_functions_listpostinit
Attempt to override final function - bis_functions_listrecompile
Attempt to override final function - bis_fnc_missiontaskslocal
Attempt to override final function - bis_fnc_missionconversationslocal
Attempt to override final function - bis_fnc_missionflow
Vehicle type HeadlessClient_F does not exist
No speaker given for Janos Dimitriadis
No speaker given for Janos Gikas
No speaker given for Kostakis Elias
No speaker given for Gerasimos Karapataki
No speaker given for Giourkas Costas
No speaker given for Janos Verga
No speaker given for Biton Dimitriadis
No speaker given for Dimitris Lara
No speaker given for Theofilos Lara
No speaker given for Kyriakos Nicolau
Strange convex component24 in a3\structures_f\households\house_small02\i_house_small_02_v1_dam_f.p3d:geometryView
Strange convex component52 in a3\structures_f\households\stone_shed\i_stone_shed_v1_dam_f.p3d:geometryView
Strange convex component24 in a3\structures_f\households\house_small02\u_house_small_02_v1_dam_f.p3d:geometryView
Vehicle type Land_Atm_01_F does not exist
Vehicle type Land_Atm_02_F does not exist
Vehicle type Land_Atm_01_F does not exist
Vehicle type Land_Atm_02_F does not exist
Vehicle type Land_Atm_01_F does not exist
Vehicle type Land_Atm_01_F does not exist
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <ex;

if (_faceTex == "\") then
{
_faces pushBack configName _faceCfg;
};
};

_fa>
  Error position: <pushBack configName _faceCfg;
};
};

_fa>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 75
Error in expression <0;
_npcName = vehicleVarName _npc;
_npc setName [_npcName,"",""];

_npc allowDam>
  Error position: <setName [_npcName,"",""];

_npc allowDam>
  Error setname: Type Object, expected Location
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 20
Error in expression <0;
_npcName = vehicleVarName _npc;
_npc setName [_npcName,"",""];

_npc allowDam>
  Error position: <setName [_npcName,"",""];

_npc allowDam>
  Error setname: Type Object, expected Location
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 20
Error in expression <0;
_npcName = vehicleVarName _npc;
_npc setName [_npcName,"",""];

_npc allowDam>
  Error position: <setName [_npcName,"",""];

_npc allowDam>
  Error setname: Type Object, expected Location
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 20
Error in expression <0;
_npcName = vehicleVarName _npc;
_npc setName [_npcName,"",""];

_npc allowDam>
  Error position: <setName [_npcName,"",""];

_npc allowDam>
  Error setname: Type Object, expected Location
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 20
Error in expression <0;
_npcName = vehicleVarName _npc;
_npc setName [_npcName,"",""];

_npc allowDam>
  Error position: <setName [_npcName,"",""];

_npc allowDam>
  Error setname: Type Object, expected Location
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 20
Error in expression <0;
_npcName = vehicleVarName _npc;
_npc setName [_npcName,"",""];

_npc allowDam>
  Error position: <setName [_npcName,"",""];

_npc allowDam>
  Error setname: Type Object, expected Location
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 20
Error in expression <ing (_buffer select [0, 1021]);
_buffer deleteRange [0, 1021];
};
};
};
};
>
  Error position: <deleteRange [0, 1021];
};
};
};
};
>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\antihack\filterExecAttempt.sqf, line 91
Error in expression <ing (_buffer select [0, 1021]);
_buffer deleteRange [0, 1021];
};
};
};
};
>
  Error position: <deleteRange [0, 1021];
};
};
};
};
>
  Error Missing ;
File mpmissions\A3Wasteland_v1.1.Stratis\server\antihack\filterExecAttempt.sqf, line 91
Error in expression <0;
_npcName = vehicleVarName _npc;
_npc setName [_npcName,"",""];

_npc allowDam>
  Error position: <setName [_npcName,"",""];

_npc allowDam>
  Error setname: Type Object, expected Location
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 20
Error in expression <0;
_npcName = vehicleVarName _npc;
_npc setName [_npcName,"",""];

_npc allowDam>
  Error position: <setName [_npcName,"",""];

_npc allowDam>
  Error setname: Type Object, expected Location
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 20
Error in expression <0;
_npcName = vehicleVarName _npc;
_npc setName [_npcName,"",""];

_npc allowDam>
  Error position: <setName [_npcName,"",""];

_npc allowDam>
  Error setname: Type Object, expected Location
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 20
Error in expression <0;
_npcName = vehicleVarName _npc;
_npc setName [_npcName,"",""];

_npc allowDam>
  Error position: <setName [_npcName,"",""];

_npc allowDam>
  Error setname: Type Object, expected Location
File mpmissions\A3Wasteland_v1.1.Stratis\server\functions\setupStoreNPC.sqf, line 20
Error in expression <mpileFinal str (_descExtPath select [0, count _descExtPath - 15]);

X_Server = f>
  Error position: <count _descExtPath - 15]);

X_Server = f>
  Error count: Type String, expected Array,Config entry
File mpmissions\A3Wasteland_v1.1.Stratis\init.sqf, line 14
control[DebugConsole]: Unexpected control type [15]
control[DebugConsole]: Unexpected control type [15]
control[MessageBox]: Unexpected control type [15]
control[MessageBox]: Unexpected control type [15]

**Comment by AgentRev** [comment]
> <h1>Version: 1.00.109911</h1>

There goes your problem.

**Comment by zhaoxg686** [comment]
OK, thank you.
