### ISSUE TITLE
extDB bug 

### ISSUE THREAD

**Issue by ImChip** [A3Wasteland/ArmA3_Wasteland.Stratis#60]
hi i got a problem
if connect to this server 
stuck to "Welcome to A3Wasteland. Please waiting ... "

rpt logs 
http://paste.imchip.ovh/igujexaxiw.tex

Nitrado game server
extDB lasted
A3Wasteland v1.1

**Comment by AgentRev** [comment]
5:54:57 "[extDB] Startup..."
	 5:54:57 "[extDB] ### Database error! [0,"No Config Option Found"]"
	 5:54:57 "[extDB] ### ERROR - Startup aborted"

That means you haven't configured your extdb-conf.ini properly, here is the default one, you need to put it in the same folder as arma3server.exe. and configure your database connection with your infos : https://gist.github.com/AgentRev/f83b125a4ac3a4b680ab#file-extdb-conf-ini-L28-L31

**Comment by ImChip** [comment]
Ty for this rep 
I use default extdb-conf.ini in nitrado install
i try to change with your extdb conf

**Comment by ImChip** [comment]
Ok its work ! 

i move db_custom in my @extDB 
and server check in /extDB/db_custom/a3wasteland.ini 

Ty man
