### ISSUE TITLE
Anti-Hack 

### ISSUE THREAD

**Issue by ImChip** [A3Wasteland/ArmA3_Wasteland.Stratis#61]
My server kick me for 

10:17:56 "ANTI-HACK: [Adj] A. Miller [BRI](XXXXXXXXXXXXXXXX) was detected for [hacked unit] with the value [B_Pilot_F]"

Any issue for this ?

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/Development_main/server/antihack/compileFuncs.sqf#L57
