### ISSUE TITLE
Lost 3 Kuma's to parking right before last reset

### ISSUE THREAD

**Issue by 40oztek** [A3Wasteland/ArmA3_Wasteland.Stratis#67]
Me an my two friends went to parking 30 minutes before restart and I saved 2 of 3 tanks one I took out of parking earlier the agia marina one, and when I saved the first tank it disappeared, I had already saved both tanks, and was towing one.

I tried to save the other one an said forget it then it disappeared too not appearing in my parking inventory 

then my friend re saved his and went to park it and it did the same thing to him 

nbd, just 150,000 gone... Yeah I don't expect to get the tanks back but id like this fixed and would like if it never happened again.

**Comment by 40oztek** [comment]
and yes I untowed the tank

**Comment by AgentRev** [comment]
This place is to report repeatable bugs with the mission in general, not to a place to claim stuff you lost on a particular server, you need to contact the server owner.
