### ISSUE TITLE
Can't open admin menu 

### ISSUE THREAD

**Issue by NEARNIPER** [A3Wasteland/ArmA3_Wasteland.Stratis#69]
hello help please, Why I can't open admin menu (I'm host on Lan) how to fix it
http://steamcommunity.com/sharedfiles/filedetails/?id=169806722
I know at workshop detail press U key twice but not working 
try repeatedly u+u+u+u+u+u still not work (my keyboard will broken)

long ago remember i play Stratis A3Wasteland with friend i can use admin menu with u key
and teleport to him and add money... wow so fun, I don't know now can't use it

uninstall arma 3 (steam) and new download - done
unsubscribe (steamworkshop) and subscribe - done

but in A3Wasteland Altis v1.2 it work so easy press u key (just only one)
http://steamcommunity.com/sharedfiles/filedetails/?id=331836884

thank you, sorry I'm bad english

**Comment by anderson2927** [comment]
Me too

**Comment by i-korob** [comment]
i think you need login as admin by type "#login _admin_pass_" in chat, at "assign role" screen. pass sets in setting file.
