### ISSUE TITLE
Players get killed instantly (revive not possible)

### ISSUE THREAD

**Issue by Silver0** [A3Wasteland/ArmA3_Wasteland.Stratis#77]
Most of the time players are dying instantly when they get shot by a gun and you have no chance to revive them. This bug encountered with the latest patch (1.54).

As Screwball said in the forums:
>Looks like FAR_revive is broken.
>You go into unconscious state only if u get shot to the legs anything else will get you killed instantly.

[Link to post on A3Wasteland Forums](http://forums.a3wasteland.com/index.php?topic=2276.0)

**Comment by AgentRev** [comment]
This is fixed in the Altis dev branch, read here: http://forums.a3wasteland.com/index.php?topic=2341.0

The revive fix: https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/9c78c8d440b87df992eb81a883f48da8ee0d4755
