### ISSUE TITLE
Unable to reach lobby when launching server

### ISSUE THREAD

**Issue by Fallen-Donkey** [A3Wasteland/ArmA3_Wasteland.Stratis#80]
Hi Guys,

Thanks for all the support so far. I have downloaded the source code packed into a pbo and launched the server. When I connect to the server I get a black screen. I can hear the "ambient noise" in the background and the server messages are displaying but purely just a black screen. here are my log files

as far as I know I have configured the wasteland server files correctly and the database 

[Fallen server logs.zip](https://github.com/A3Wasteland/ArmA3_Wasteland.Stratis/files/297503/Fallen.server.logs.zip)

**Comment by i-korob** [comment]
You need wait much more. This is initialization time.
