### ISSUE TITLE
New Parking System

### ISSUE THREAD

**Issue by Soloknight** [A3Wasteland/ArmA3_Wasteland.Stratis#81]
2 bugs I seen so far, Great job btw
1. In Stratis the desk and computer floating in the air
2. If there is a resupply truck near by it can be parked and the ownership is changed

**Comment by AgentRev** [comment]
oops lol I forgot about that.

**Comment by Soloknight** [comment]
One other bug, maybe just on our server because I use #s for the skins names, but when you retrieve the vehicle there no vehicle skin on it

**Comment by AgentRev** [comment]
Skin names, you mean what is displayed in the store? The name isn't saved, only the texture string; the # chars don't cause any problems, they are used for the normal plain color skins

**Comment by Soloknight** [comment]
forever reason, the vehicles spawn back with just a empty frame. I'm looking for anything I might have missed

**Comment by AgentRev** [comment]
what's a frame?

**Comment by Soloknight** [comment]
Vehicle with tires and frame no skins or shell

**Comment by Soloknight** [comment]
For Stratis
this is my store config for textures
    [ // Main colors
        "All",
        [
            ["Black", _color + "(0.01,0.01,0.01,1)"], // #(argb,8,8,3)color(0.1,0.1,0.1,0.1)
            ["Gray", _color + "(0.15,0.151,0.152,1)"], // #(argb,8,8,3)color(0.5,0.51,0.512,0.3)
            ["White", _color + "(0.75,0.75,0.75,1)"], // #(argb,8,8,3)color(1,1,1,0.5)
            ["Dark Blue", _color + "(0,0.05,0.15,1)"], // #(argb,8,8,3)color(0,0.3,0.6,0.05)
            ["Blue", _color + "(0,0.03,0.5,1)"], // #(argb,8,8,3)color(0,0.2,1,0.75)
            ["Teal", _color + "(0,0.3,0.3,1)"], // #(argb,8,8,3)color(0,1,1,0.15)
            ["Green", _color + "(0,0.5,0,1)"], // #(argb,8,8,3)color(0,1,0,0.15)
            ["Yellow", _color + "(0.5,0.4,0,1)"], // #(argb,8,8,3)color(1,0.8,0,0.4)
            ["Orange", _color + "(0.4,0.09,0,1)"], // #(argb,8,8,3)color(1,0.5,0,0.4)
            ["Red", _color + "(0.45,0.005,0,1)"], // #(argb,8,8,3)color(1,0.1,0,0.3)
            ["Pink", _color + "(0.5,0.03,0.3,1)"], // #(argb,8,8,3)color(1,0.06,0.6,0.5)
            ["Purple", _color + "(0.1,0,0.3,1)"], // #(argb,8,8,3)color(0.8,0,1,0.1)
            ["NATO Tan", _texDir + "nato.paa"], // #(argb,8,8,3)color(0.584,0.565,0.515,0.3)
            ["CSAT Brown", _texDir + "csat.paa"], // #(argb,8,8,3)color(0.624,0.512,0.368,0.3)
            ["AAF Green", _texDir + "aaf.paa"], // #(argb,8,8,3)color(0.546,0.59,0.363,0.2)
            ["Bloodshot", _texDir + "17_P.paa"],
            ["Carbon", _texDir + "19_P.paa"],
            ["Confederate", _texDir + "20_P.paa"],
            //["Denim", _texDir + "21_P.paa"],
            ["Digital", _texDir + "22_P.paa"],
            ["Digital Black", _texDir + "23_P.paa"],
            ["Digital Desert", _texDir + "24_P.paa"],
            ["Digital Woodland", _texDir + "25_P.paa"],
            ["Doritos", _texDir + "26_P.paa"],
            ["Drylands", _texDir + "27_P.paa"],
            ["Hello Kitty", _texDir + "28_P.paa"],
            ["Hex", _texDir + "29_P.paa"],
            ["Hippie", _texDir + "30_P.paa"],
            //["ISIS", _texDir + "isis.paa"],
            ["Leopard", _texDir + "31_P.paa"],
            ["Mountain Dew", _texDir + "32_P.paa"],
            ["'Murica", _texDir + "murica.paa"],
            //["Nazi", _texDir + "nazi.paa"],
            ["Orange Camo", _texDir + "18_P.paa"],
            ["Pink Camo", _texDir + "33_P.paa"],
            ["Red Camo", _texDir + "34_P.paa"],
            ["Pride", _texDir + "35_P.paa"],
            //["Psych", _texDir + "36_P.paa"],
            ["Rusty", _texDir + "37_P.paa"],
            ["Sand", _texDir + "38_P.paa"],
            ["Snake", _texDir + "39_P.paa"],
            ["Stripes", _texDir + "40_P.paa"],
            ["Stripes 2", _texDir + "41_P.paa"],
            ["Stripes 3", _texDir + "42_P.paa"],
            ["Swamp", _texDir + "43_P.paa"],
            ["Tiger", _texDir + "44_P.paa"],
            //["Trippy", _texDir + "45_P.paa"],
            ["Union Jack", _texDir + "46_P.paa"],
            ["Urban", _texDir + "47_P.paa"],
            ["Weed", _texDir + "48_P.paa"],
            ["Woodland", _texDir + "49_P.paa"],
            ["Woodland Dark", _texDir + "50_P.paa"],
            ["Woodland Tiger", _texDir + "51_P.paa"]
        ]
    ],

**Comment by AgentRev** [comment]
side question - what's the point of renaming the PAAs? If I decide to update one of the textures it will causes conflicts for no good reason.

**Comment by Soloknight** [comment]
It was easier to pull from the database to place on player uniforms for donators

**Comment by AgentRev** [comment]
I don't see how it would make it easier script-wise. You're not doing this manually aren't you?

**Comment by Soloknight** [comment]
I was at the time, had a column name customUniform place a 6 in it and it would pull the skin for the detonator when they logged in. I can change it back, but I need to change the Paint uniform script we use also no big deal.

**Comment by AgentRev** [comment]
> detonator

You blow up your donators? What is this!?

**Comment by Soloknight** [comment]
lol dam auto correct stuff

**Comment by Soloknight** [comment]
Ok I converted all skins back etc. but when you retrieve vehicle its just a empty shell just tires mostly 

if you want to test it: 104.128.62.2:2302

it works for nomal spawn vehicles

**Comment by AgentRev** [comment]
fixed; it was due to double backslashes added for extDB also present in the live parking variable, which is read directly on retrieval.
