### ISSUE TITLE
Mission Vehicles

### ISSUE THREAD

**Issue by Soloknight** [A3Wasteland/ArmA3_Wasteland.Stratis#82]
Main Battle Tank mission

get this error in the logs after completing it

14:27:40 Error in expression <ehicle _vehicle;
};

_successExec =
{

[_veh, 1] call A3W_fnc_setLockState; 

_s>
14:27:40   Error position: <_veh, 1] call A3W_fnc_setLockState; 

_s>
14:27:40   Error Undefined variable in expression: _veh
14:27:40 File mpmissions__cur_mp.Stratis\server\missions\mainMissions\mission_VehicleCapture.sqf, line 192

now [_veh, 1] call A3W_fnc_setLockState; // Unlock
Should be [_vehicle, 1] call A3W_fnc_setLockState; // Unlock

**Comment by AgentRev** [comment]
already fixed not pushed yet

**Comment by Soloknight** [comment]
your a maniac, I going to push another donation this week ;-)

**Comment by marcoroesch** [comment]
The Boot are inside the Vehicle in the Gunner of the Main Battle Tank and Anti Aircraft Vehicle, what is the solution?
