### ISSUE TITLE
Complaint against "Paul tower"

### ISSUE THREAD

**Issue by 0Mikeehrmantraut0** [A3Wasteland/ArmA3_Wasteland.Stratis#87]
This person used usebug and crossed end walls has to kill this enemy is

**Comment by AgentRev** [comment]
can please correctly english speak, thank!! :trumpet:

**Comment by 0Mikeehrmantraut0** [comment]
sorry im french

**Comment by AgentRev** [comment]
oui donc ceci n'est pas l'endroit approprié pour loger des complaintes, nous sommes seulement l'équipe de développement et pas plus, vous devez contacter l'admin du serveur où le problème a eu lieu.
