### ISSUE TITLE
Money Drop Hack

### ISSUE THREAD

**Issue by proqress** [A3Wasteland/ArmA3_Wasteland.Stratis#91]
Since 3 or 4 days people joins and immediately starts to drop $50ks infinitely and himself gets max ATM money. Is this about my improper battleye configuration or are you doing/planning something about this?

Steam IDs: 76561198372583521 , 76561198373173683

PS: RPT output of the incident moment:

21:10:54 "Player connected: Cheese (76561198373173683)"
21:10:55 "updateConnectingClients [Player: R Alpha 4-1:1 (Cheese) REMOTE] [JIP: true]"
21:10:56 Scripting function 'bis_fnc_execvm' is not allowed to be remotely executed
21:10:56 Server: Object 21:84 not found (message Type_93)
21:10:57 "pvar_requestPlayerData: [164,R Alpha 4-1:1 (Cheese) REMOTE,R Alpha 4-1:1 (Cheese) REMOTE]"
21:10:58 Error: Object(164 : 6) not found
21:10:58 Error: Object(164 : 7) not found
21:10:58 Error: Object(164 : 8) not found
21:10:58 Error: Object(164 : 6) not found
21:10:58 Error: Object(164 : 7) not found
21:10:58 Error: Object(164 : 8) not found
21:11:00 Server: Object 21:129 not found (message Type_93)
21:11:00 Server: Object 21:128 not found (message Type_93)
21:11:00 Server: Object 21:84 not found (message Type_121)
21:11:01 Server: Object 21:84 not found (message Type_93)
21:11:04 "A3W - 63 baseparts and objects have been saved with extDB"
21:11:06 Server: Object 21:84 not found (message Type_93)
21:11:11 Server: Object 21:84 not found (message Type_121)
21:11:12 Server: Object 21:129 not found (message Type_121)
21:11:13 Server: Object 21:84 not found (message Type_93)
21:11:18 Server: Object 21:84 not found (message Type_93)
21:11:19 Server: Object 21:128 not found (message Type_121)
21:11:21 Error: Object(146 : 15) not found
21:11:22 Server: Object 21:84 not found (message Type_121)
21:11:23 Server: Object 21:128 not found (message Type_93)
21:11:23 Server: Object 21:129 not found (message Type_93)
21:11:24 Server: Object 21:84 not found (message Type_93)
21:11:29 Server: Object 21:84 not found (message Type_93)
21:11:29 "A3W - 44 vehicles have been saved with extDB"
21:11:32 Server: Object 21:84 not found (message Type_121)
21:11:34 Server: Object 21:84 not found (message Type_93)
21:11:39 Server: Object 21:84 not found (message Type_93)
21:11:42 Server: Object 21:84 not found (message Type_121)
21:11:44 Server: Object 21:129 not found (message Type_93)
21:11:44 Server: Object 21:128 not found (message Type_93)
21:11:45 Server: Object 21:84 not found (message Type_93)
21:11:46 Server: Object 129:97 not found (message Type_443)
21:11:46 Server: Object 129:96 not found (message Type_121)
21:11:47 Server: Object 129:98 not found (message Type_121)
21:11:47 Error: Object(129 : 97) not found
21:11:48 Client: Object 138:82 (type Type_92) not found.
21:11:48 Client: Object 138:82 (type Type_93) not found.
21:11:48 Client: Object 138:82 (type Type_443) not found.
21:11:50 "A3W - 5 mines have been saved with extDB"
21:11:51 Server: Object 21:84 not found (message Type_93)
21:11:51 Client: Remote object 134:0 not found
21:11:52 Server: Object 21:129 not found (message Type_121)
21:11:53 Server: Object 21:84 not found (message Type_121)
21:11:58 Server: Object 21:84 not found (message Type_93)
21:12:01 Server: Object 21:128 not found (message Type_121)
21:12:04 Server: Object 21:84 not found (message Type_93)
21:12:05 Server: Object 21:84 not found (message Type_121)
21:12:08 Server: Object 21:128 not found (message Type_93)
21:12:08 Server: Object 21:129 not found (message Type_93)
21:12:09 Server: Object 138:88 not found (message Type_443)
21:12:09 Server: Object 138:87 not found (message Type_93)
21:12:09 Server: Object 138:89 not found (message Type_443)
21:12:09 Server: Object 21:84 not found (message Type_93)
21:12:09 Error: Object(138 : 88) not found
21:12:09 Error: Object(138 : 87) not found
21:12:09 Error: Object(138 : 89) not found
21:12:15 Server: Object 21:84 not found (message Type_93)
21:12:15 Error: Object(130 : 85) not found
21:12:15 Server: Object 21:84 not found (message Type_121)
21:12:21 Server: Object 21:84 not found (message Type_93)
21:12:23 Error: Object(162 : 9) not found
21:12:26 Server: Object 21:84 not found (message Type_121)
21:12:26 Server: Object 21:84 not found (message Type_93)
21:12:27 "A3W - 63 baseparts and objects have been saved with extDB"
21:12:30 Server: Object 130:89 not found (message Type_121)
21:12:30 Server: Object 130:92 not found (message Type_443)
21:12:30 Server: Object 130:91 not found (message Type_121)
21:12:30 Server: Object 130:93 not found (message Type_443)
21:12:30 Server: Object 21:129 not found (message Type_93)
21:12:30 Server: Object 21:128 not found (message Type_93)
21:12:30 Error: Object(130 : 92) not found
21:12:32 Unaccessible
21:12:32 Server: Object 21:84 not found (message Type_93)
21:12:34 Scripting function 'bis_fnc_execvm' is not allowed to be remotely executed
21:12:36 Server: Object 21:129 not found (message Type_121)
21:12:36 Error: Object(161 : 10) not found
21:12:36 Error: Object(161 : 11) not found
21:12:38 Server: Object 21:84 not found (message Type_121)
21:12:39 Server: Object 21:84 not found (message Type_93)
21:12:42 Server: Object 144:21 not found (message Type_121)
21:12:42 Server: Object 144:22 not found (message Type_121)
21:12:42 Server: Object 144:23 not found (message Type_121)
21:12:44 Server: Object 21:128 not found (message Type_121)
21:12:45 Server: Object 21:84 not found (message Type_93)
21:12:48 Server: Object 21:84 not found (message Type_121)
21:12:50 Server: Object 21:84 not found (message Type_93)
21:12:51 Server: Object 161:15 not found (message Type_121)
21:12:51 Server: Object 161:17 not found (message Type_121)
21:12:51 Server: Object 161:18 not found (message Type_121)
21:12:52 Error: Object(153 : 20) not found
21:12:55 NetServer::SendMsg: cannot find channel #84360426, users.card=24
21:12:55 NetServer: users.get failed when sending to 84360426
21:12:55 Message not sent - error 0, message ID = ffffffff, to 84360426 (<no>)
21:12:55 Server: Object 21:128 not found (message Type_93)
21:12:55 Server: Object 21:129 not found (message Type_93)
21:12:56 "A3W - 41 vehicles have been saved with extDB"
21:12:57 Server: Object 21:84 not found (message Type_93)
21:13:00 Server: Object 21:84 not found (message Type_121)
21:13:02 Server: Object 21:84 not found (message Type_93)
21:13:04 Error in expression <f"

if (!isServer) exitWith {};

params [["_unit",objNull,[objNull]], "",>
21:13:04   Error position: <params [["_unit",objNull,[objNull]], "",>
21:13:04   Error Params: Type Bool, expected Array
21:13:04 File mpmissions\__cur_mp.Stratis\server\functions\serverPlayerDied.sqf, line 11
21:13:04 Error in expression <f"

if (!isServer) exitWith {};

params [["_unit",objNull,[objNull]], "",>
21:13:04   Error position: <params [["_unit",objNull,[objNull]], "",>
21:13:04   Error Params: Type Bool, expected Array
21:13:04 File mpmissions\__cur_mp.Stratis\server\functions\serverPlayerDied.sqf, line 11
21:13:04 Error in expression <f"

if (!isServer) exitWith {};

params [["_unit",objNull,[objNull]], "",>
21:13:04   Error position: <params [["_unit",objNull,[objNull]], "",>
21:13:04   Error Params: Type Bool, expected Array
21:13:04 File mpmissions\__cur_mp.Stratis\server\functions\serverPlayerDied.sqf, line 11
21:13:04 Error in expression <f"

if (!isServer) exitWith {};

params [["_unit",objNull,[objNull]], "",>
21:13:04   Error position: <params [["_unit",objNull,[objNull]], "",>
21:13:04   Error Params: Type Bool, expected Array
21:13:04 File mpmissions\__cur_mp.Stratis\server\functions\serverPlayerDied.sqf, line 11
21:13:08 Server: Object 21:84 not found (message Type_93)
21:13:08 Server: Object 153:24 not found (message Type_121)
21:13:08 Server: Object 153:27 not found (message Type_121)
21:13:08 Server: Object 153:26 not found (message Type_121)
21:13:08 Server: Object 153:28 not found (message Type_121)
21:13:09 Out of path-planning region for C Alpha 1-4:7 at 4318.0,6789.0, node type Road
21:13:09 Error C Alpha 1-4:7: Invalid path from [4321.60, 133.73, 6790.00] to [4320.98, 126.58, 6784.84].
21:13:10 Server: Object 21:84 not found (message Type_121)
21:13:11 Out of path-planning region for C Alpha 1-4:8 at 4318.0,6794.0, node type Road
21:13:11 Error C Alpha 1-4:8: Invalid path from [4321.75, 133.62, 6793.00] to [4322.50, 126.01, 6796.50].
21:13:12 "WASTELAND SERVER - Side Mission started: Town Invasion"
21:13:13 Error compiling '' in 'HitPelvis'
21:13:13 Error compiling '' in 'HitAbdomen'
21:13:13 Error compiling '' in 'HitDiaphragm'
21:13:13 Error compiling '' in 'HitChest'
21:13:13 Error compiling '' in 'HitArms'
21:13:13 Error compiling '' in 'HitLegs'
21:13:13 Server: Object 21:84 not found (message Type_93)
21:13:14 Error compiling '' in 'HitPelvis'
21:13:14 Error compiling '' in 'HitAbdomen'
21:13:14 Error compiling '' in 'HitDiaphragm'
21:13:14 Error compiling '' in 'HitChest'
21:13:14 Error compiling '' in 'HitArms'
21:13:14 Error compiling '' in 'HitLegs'
21:13:14 Error compiling '' in 'HitPelvis'
21:13:14 Error compiling '' in 'HitAbdomen'
21:13:14 Error compiling '' in 'HitDiaphragm'
21:13:14 Error compiling '' in 'HitChest'
21:13:14 Error compiling '' in 'HitArms'
21:13:14 Error compiling '' in 'HitLegs'
21:13:14 Error compiling '' in 'HitPelvis'
21:13:14 Error compiling '' in 'HitAbdomen'
21:13:14 Error compiling '' in 'HitDiaphragm'
21:13:14 Error compiling '' in 'HitChest'
21:13:14 Error compiling '' in 'HitArms'
21:13:14 Error compiling '' in 'HitLegs'
21:13:14 No speaker given for Shaan Sekibo
21:13:14 Error compiling '' in 'HitPelvis'
21:13:14 Error compiling '' in 'HitAbdomen'
21:13:14 Error compiling '' in 'HitDiaphragm'
21:13:14 Error compiling '' in 'HitChest'
21:13:14 Error compiling '' in 'HitArms'
21:13:14 Error compiling '' in 'HitLegs'
21:13:17 "WASTELAND SERVER - Side Mission waiting to be finished: Town Invasion"
21:13:17 "A3W - 5 mines have been saved with extDB"
21:13:17 Server: Object 21:128 not found (message Type_93)
21:13:17 Server: Object 21:129 not found (message Type_93)
21:13:18 Server: Object 21:129 not found (message Type_121)
21:13:19 Server: Object 21:84 not found (message Type_93)
21:13:21 Server: Object 21:84 not found (message Type_121)
21:13:25 Server: Object 129:105 not found (message Type_443)
21:13:25 Server: Object 129:104 not found (message Type_121)
21:13:25 Server: Object 129:106 not found (message Type_443)
21:13:26 Error: Object(129 : 105) not found
21:13:26 Error: Object(129 : 106) not found
21:13:27 Server: Object 21:84 not found (message Type_93)
21:13:28 Server: Object 21:128 not found (message Type_121)
21:13:28 Error: Object(144 : 24) not found
21:13:32 Server: Object 21:84 not found (message Type_93)
21:13:33 Server: Object 21:84 not found (message Type_121)
21:13:37 Server: Object 21:84 not found (message Type_93)
21:13:41 Server: Object 21:129 not found (message Type_93)
21:13:41 Server: Object 21:128 not found (message Type_93)
21:13:42 Server: Object 126:84 not found (message Type_121)
21:13:42 Server: Object 126:86 not found (message Type_93)
21:13:42 Server: Object 126:87 not found (message Type_121)
21:13:42 Server: Object 126:88 not found (message Type_121)
21:13:42 Error: Object(126 : 86) not found
21:13:43 Server: Object 21:84 not found (message Type_93)
21:13:44 Server: Object 21:84 not found (message Type_121)
21:13:46 Server: Object 2:5943 not found (message Type_274)
21:13:46 Server: Object 2:5948 not found (message Type_274)
21:13:46 Server: Object 2:5953 not found (message Type_274)
21:13:46 Server: Object 2:5958 not found (message Type_274)
21:13:46 Error: Object(144 : 25) not found
21:13:48 Unaccessible
21:13:49 Server: Object 21:84 not found (message Type_93)
21:13:51 Error in expression <f"

if (!isServer) exitWith {};

params [["_unit",objNull,[objNull]], "",>
21:13:51   Error position: <params [["_unit",objNull,[objNull]], "",>
21:13:51   Error Params: Type Bool, expected Array
21:13:51 File mpmissions\__cur_mp.Stratis\server\functions\serverPlayerDied.sqf, line 11
21:13:51 Error in expression <f"

if (!isServer) exitWith {};

params [["_unit",objNull,[objNull]], "",>
21:13:51   Error position: <params [["_unit",objNull,[objNull]], "",>
21:13:51   Error Params: Type Bool, expected Array
21:13:51 File mpmissions\__cur_mp.Stratis\server\functions\serverPlayerDied.sqf, line 11
21:13:52 Client: Remote object 163:0 not found
21:13:54 Server: Object 21:84 not found (message Type_121)
21:13:54 Scripting function 'bis_fnc_execvm' is not allowed to be remotely executed
21:13:55 Server: Object 21:84 not found (message Type_93)
21:13:55 "A3W - 63 baseparts and objects have been saved with extDB"
21:14:00 Server: Object 21:84 not found (message Type_93)
21:14:01 Server: Object 21:129 not found (message Type_121)
21:14:01 Server: Object 144:29 not found (message Type_93)
21:14:01 Server: Object 144:30 not found (message Type_121)
21:14:01 Server: Object 144:31 not found (message Type_93)
21:14:02 Error: Object(144 : 29) not found
21:14:03 Server: Object 21:128 not found (message Type_93)
21:14:03 Server: Object 21:129 not found (message Type_93)
21:14:04 Server: Object 21:84 not found (message Type_121)
21:14:05 Server: Object 21:84 not found (message Type_93)
21:14:08 Server: Object 21:128 not found (message Type_121)
21:14:10 Server: Object 21:84 not found (message Type_93)
21:14:11 Client: Object 157:11 (type Type_443) not found.
21:14:11 Client: Object 157:11 (type Type_92) not found.
21:14:11 Client: Object 157:11 (type Type_93) not found.
21:14:12 Error: Object(157 : 12) not found
21:14:13 Error: Object(160 : 12) not found
21:14:13 Error: Object(160 : 11) not found
21:14:14 Server: Object 21:84 not found (message Type_121)
21:14:15 Server: Object 21:84 not found (message Type_93)
21:14:18 Error: Object(129 : 108) not found
21:14:20 Server: Object 138:96 not found (message Type_121)
21:14:20 Server: Object 138:97 not found (message Type_121)
21:14:21 Server: Object 138:98 not found (message Type_121)
21:14:21 Server: Object 21:84 not found (message Type_93)
21:14:21 "A3W - 40 vehicles have been saved with extDB"
21:14:21 Error: Object(166 : 5) not found
21:14:21 Error: Object(166 : 6) not found
21:14:22 Error: Object(162 : 10) not found
21:14:24 Server: Object 21:128 not found (message Type_93)
21:14:24 Server: Object 21:129 not found (message Type_93)
21:14:25 Server: Object 21:84 not found (message Type_121)
21:14:26 Server: Object 157:16 not found (message Type_121)
21:14:26 Server: Object 157:18 not found (message Type_93)
21:14:26 Server: Object 157:19 not found (message Type_121)
21:14:26 Server: Object 157:20 not found (message Type_121)
21:14:26 Server: Object 160:16 not found (message Type_121)
21:14:26 Server: Object 21:84 not found (message Type_93)
21:14:26 Server: Object 160:18 not found (message Type_93)
21:14:26 Server: Object 160:19 not found (message Type_443)
21:14:26 Server: Object 160:20 not found (message Type_443)
21:14:26 Error: Object(157 : 18) not found
21:14:27 Error: Object(160 : 18) not found
21:14:27 Error: Object(160 : 19) not found
21:14:27 Error: Object(160 : 18) not found
21:14:27 Error: Object(160 : 19) not found
21:14:31 Server: Object 21:84 not found (message Type_93)
21:14:34 Server: Object 21:84 not found (message Type_121)
21:14:35 Client: Object 115:131 (type Type_92) not found.
21:14:35 Client: Object 115:131 (type Type_443) not found.
21:14:35 Client: Object 115:131 (type Type_93) not found.
21:14:37 Server: Object 21:84 not found (message Type_93)
21:14:40 Server: Object 21:129 not found (message Type_121)
21:14:41 "A3W - 5 mines have been saved with extDB"
21:14:42 Server: Object 21:84 not found (message Type_93)
21:14:45 Server: Object 21:84 not found (message Type_121)
21:14:46 Server: Object 21:128 not found (message Type_93)
21:14:46 Server: Object 21:129 not found (message Type_93)
21:14:46 Error: Object(144 : 32) not found
21:14:48 Server: Object 21:128 not found (message Type_121)
21:14:48 Server: Object 21:84 not found (message Type_93)
21:14:54 Server: Object 21:84 not found (message Type_93)
21:14:54 Server: Object 115:137 not found (message Type_93)
21:14:54 Server: Object 115:138 not found (message Type_443)
21:14:54 Server: Object 115:139 not found (message Type_443)
21:14:55 Error: Object(115 : 137) not found
21:14:55 Error: Object(115 : 138) not found
21:14:55 Error: Object(115 : 139) not found
21:14:55 Server: Object 122:28 not found (message Type_93)
21:14:55 Server: Object 122:27 not found (message Type_93)
21:14:56 Server: Object 21:84 not found (message Type_121)
21:14:57 Server: Object 122:28 not found (message Type_121)
21:14:59 Server: Object 122:27 not found (message Type_121)
21:15:00 Server: Object 21:84 not found (message Type_93)
21:15:05 Server: Object 21:84 not found (message Type_93)
21:15:06 Server: Object 21:84 not found (message Type_121)
21:15:08 Server: Object 21:128 not found (message Type_93)
21:15:08 Server: Object 21:129 not found (message Type_93)
21:15:10 Server: Object 21:84 not found (message Type_93)
21:15:16 Server: Object 21:84 not found (message Type_93)
21:15:16 Server: Object 21:84 not found (message Type_121)
21:15:17 "A3W - 63 baseparts and objects have been saved with extDB"
21:15:17 Server: Object 122:27 not found (message Type_93)
21:15:17 Server: Object 122:28 not found (message Type_93)
21:15:20 Server: Object 21:129 not found (message Type_121)
21:15:21 Server: Object 21:84 not found (message Type_93)
21:15:26 Server: Object 21:84 not found (message Type_121)
21:15:26 Error: Object(101 : 45) not found
21:15:26 Server: Object 21:84 not found (message Type_93)
21:15:27 Server: Object 21:128 not found (message Type_121)
21:15:29 Server: Object 21:128 not found (message Type_93)
21:15:29 Server: Object 21:129 not found (message Type_93)
21:15:31 Server: Object 21:84 not found (message Type_93)
21:15:32 Server: Object 161:25 not found (message Type_121)
21:15:32 Server: Object 161:27 not found (message Type_121)
21:15:32 Server: Object 161:28 not found (message Type_121)
21:15:32 Server: Object 161:29 not found (message Type_121)
21:15:33 "SERVER CLEANUP: Deleted 18 expired objects"
21:15:36 Server: Object 21:84 not found (message Type_121)
21:15:36 Server: Object 122:28 not found (message Type_121)
21:15:37 Server: Object 21:84 not found (message Type_93)
21:15:38 Server: Object 122:27 not found (message Type_93)
21:15:38 Server: Object 122:28 not found (message Type_93)
21:15:39 Server: Object 122:27 not found (message Type_121)
21:15:39 "SERVER CLEANUP: Deleted 6 empty groups"
21:15:42 Server: Object 21:84 not found (message Type_93)
21:15:42 Error: Object(164 : 9) not found
21:15:42 "A3W - 39 vehicles have been saved with extDB"
21:15:45 Server: Object 21:84 not found (message Type_121)
21:15:46 Error: Object(164 : 10) not found
21:15:47 Server: Object 21:84 not found (message Type_93)
21:15:47 Error: Object(164 : 11) not found
21:15:50 Server: Object 21:128 not found (message Type_93)
21:15:50 Server: Object 21:129 not found (message Type_93)
21:15:53 Server: Object 21:84 not found (message Type_93)
21:15:54 Error: Object(164 : 12) not found
21:15:55 Error: Object(164 : 13) not found
21:15:56 Server: Object 21:84 not found (message Type_121)
21:15:56 Error: Object(164 : 14) not found
21:15:57 Error: Object(164 : 15) not found
21:15:58 Error: Object(164 : 16) not found
21:16:00 Error: Object(164 : 17) not found
21:16:00 Server: Object 21:84 not found (message Type_93)
21:16:01 Error: Object(164 : 18) not found
21:16:01 Server: Object 122:27 not found (message Type_93)
21:16:01 Server: Object 122:28 not found (message Type_93)
21:16:01 Server: Object 21:129 not found (message Type_121)
21:16:03 Error: Object(164 : 20) not found
21:16:03 "A3W - 5 mines have been saved with extDB"
21:16:05 Error: Object(164 : 21) not found
21:16:06 Server: Object 21:84 not found (message Type_93)
21:16:06 Error: Object(164 : 22) not found
21:16:07 Error: Object(164 : 23) not found
21:16:08 Server: Object 21:84 not found (message Type_121)
21:16:08 Error: Object(164 : 24) not found
21:16:09 Server: Object 21:128 not found (message Type_121)
21:16:11 Server: Object 21:84 not found (message Type_93)
21:16:11 NetServer::SendMsg: cannot find channel #68347834, users.card=23
21:16:11 NetServer: users.get failed when sending to 68347834
21:16:11 Message not sent - error 0, message ID = ffffffff, to 68347834 (Cheese)
21:16:11 NetServer::SendMsg: cannot find channel #68347834, users.card=23
21:16:11 NetServer: users.get failed when sending to 68347834
21:16:11 Message not sent - error 0, message ID = ffffffff, to 68347834 (Cheese)
21:16:11 NetServer::SendMsg: cannot find channel #68347834, users.card=23
21:16:11 NetServer: users.get failed when sending to 68347834
21:16:11 Message not sent - error 0, message ID = ffffffff, to 68347834 (Cheese)
21:16:12 "Player disconnected: Cheese (76561198373173683)"
21:16:12 No player found for channel 1063146048 - message ignored
21:16:12 Client: Remote object 164:0 not found
21:16:12 "HandleDisconnect - [""Cheese"",""76561198373173683""] - alive: true - local: true - isPlayer: false - group: R Alpha 4-1"

**Comment by ghost** [comment]
all the rpt tells me is that you are not using revs latest comits especial this one https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/983de3ea96de8c95cdafcb8106f4564a46f488a6

maybe they were just hacking script kiddies ?

**Comment by proqress** [comment]
This looks like fixed by commit 0c0e2c8. Closing issue.
