### ISSUE TITLE
Issue with Naval Pier

### ISSUE THREAD

**Issue by proqress** [A3Wasteland/ArmA3_Wasteland.Stratis#93]
Since Naval Pier is not playable without APEX, people without APEX can't play on the mission.

http://steamcommunity.com/sharedfiles/filedetails/?id=927383336 for error.

**Comment by AgentRev** [comment]
This is pretty retarded, I thought we could use props from Apex without needing to purchase it, like vehicles and guns... The stairs I put on the carrier are from Apex too... god fucking damnit

**Comment by proqress** [comment]
I checked and done tests without apex content. Carrier can be used without jets dlc. Remove pier, some concretes and fire stairs it works.

**Comment by AgentRev** [comment]
should be good now

**Comment by Soloknight** [comment]
Just take them out of the addons in the mission.sqm.

**Comment by hobart666** [comment]
Ye mon apex props have been my nemesis since the were released, I have a friend building structures with xcam and am constantly having to remove any apex props because of this soviet code bis brushed off the table for us to pick at.

**Comment by AgentRev** [comment]
> Just take them out of the addon in the mission.sqm

You are right, I forgot that, fixed now.
