### ISSUE TITLE
Malden Map

### ISSUE THREAD

**Issue by AlexGnatko** [A3Wasteland/ArmA3_Wasteland.Stratis#95]
Hi guys!

I invite you to take a look at the Malden map for ArmA3_Wasteland that I made based on the Stratis map.

https://github.com/AlexGnatko/ArmA3_Wasteland.Malden

Relocated all the markers, stores, missions, town, etc.

Or you can visit to play, 5.9.88.16:2302

Looking forward for you comments and maybe adding the map to your website and to your team's repositories.

I'm sorry for posting that in the issues, found no better place to do that.

**Comment by odst910** [comment]
I loaded the mission up in the editor and all you did was merge everything so I have to replace everything I thought you did that. :(

**Comment by AgentRev** [comment]
I am currently working on an official Malden layout, based on the [A3Armory version](https://github.com/A3Armory/A3A_A3Wasteland.Malden/blob/074d2e3852b27a0bb8776ed521c5b3e3ea585045/mission.sqm), should be ready tomorrow

**Comment by odst910** [comment]
Yes! Thank you very much spent the past few days trying to do it myself but couldn't get it working 100%

**Comment by AlexGnatko** [comment]
In fact I've relocated every single object I copied from the Stratis map to new locations on the Malden map, and in my view it's pretty good. I played the map a bit (unfortunately don't have much time for playing) and it felt pretty solid, apart from some glitches like vehicle store spawning cars in the water (which was fixed by moving the spawn locations a bit). I've also added navigation markers for convoy paths, this way it's much easier than entering coordinates.

**Comment by odst910** [comment]
Hi again, I looked at my profile and realized that I had put the mission under my other profile so that was my issue. Sorry for the initial response I was very tired.

**Comment by AlexGnatko** [comment]
Hi! :)

Then I'm waiting for a more focused review of the mission, if you're interested. In my opinion the map is very playable. Though I haven't tested every store and every mission, there may be glitches that can only be seen when played.
