### ISSUE TITLE
Select in Admin menu does nothing.

### ISSUE THREAD

**Issue by 1datatec** [A3Wasteland/ArmA3_Wasteland.Stratis#96]
Just set up latest mission with extdb3. Used A3W_extDB3_pack. Disabled debug mode by commenting out the define. Everything works great but i start the server and on blue/red/green selection screen i login as admin. But then i can't select anything in admin menu. The menu shows up when i press U. When i press escape i do see the console. But when i choose something in menu and click Select nothing happens.
RPT: https://pastebin.com/2XQWseu1
No errors in sql logs, all looks good in there and everything else works great. Please advice

**Comment by AgentRev** [comment]
The admin menu is non-functional before mission hints starting showing, due to startup lag; did you wait until that point before trying to use it?

**Comment by 1datatec** [comment]
I think i disabled these hints. What file is it? Are they required? Here you can see that server was up for over an hour and its not working. I also tried with infistar off, still Select does nothing.
It was exactly the same on pure vanilla mission for me before any customizations.
https://youtu.be/Lsjm3VhBpoE
Thanks!

**Comment by AgentRev** [comment]
Are you running the game with `-showScriptErrors` ?

The RPT log you gave is for the server, the admin menu is client-side

**Comment by dima056** [comment]
Getting

**Comment by 1datatec** [comment]
While setting up server I just blindly copied admins.sqf from \server to A3Wasteland_settings. Had to remove this part:
```
if (!isServer) exitWith {};

if (loadFile (externalConfigFolder + "\admins.sqf") != "") then
{
	call compile preprocessFileLineNumbers (externalConfigFolder + "\admins.sqf");
}
else
{
```
It all works now, sorry!
